export const SERVER_URI = process.env.SERVER_URI || 'http://localhost:3000';

export const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED';

export const LIST_CONTACTS_REQUEST = 'LIST_CONTACTS_REQUEST';
export const LIST_CONTACTS_SUCCESS = 'LIST_CONTACTS_SUCCESS';
export const LIST_CONTACTS_FAILED = 'LIST_CONTACTS_FAILED';

export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAILED = 'GET_CONTACT_FAILED';

export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';

export const NAME_CHANGE = 'NAME_CHANGE';
export const PHONE_CHANGE = 'PHONE_CHANGE';
export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const BILLING_ADDRESS_FIELD1_CHANGE = 'BILLING_ADDRESS_FIELD1_CHANGE';
export const BILLING_ADDRESS_FIELD2_CHANGE = 'BILLING_ADDRESS_FIELD2_CHANGE';
export const BILLING_ADDRESS_FIELD3_CHANGE = 'BILLING_ADDRESS_FIELD3_CHANGE';
export const SAME_ADDRESS_CHANGE = 'SAME_ADDRESS_CHANGE';
export const SHIPPING_ADDRESS_FIELD1_CHANGE = 'SHIPPING_ADDRESS_FIELD1_CHANGE';
export const SHIPPING_ADDRESS_FIELD2_CHANGE = 'SHIPPING_ADDRESS_FIELD2_CHANGE';
export const SHIPPING_ADDRESS_FIELD3_CHANGE = 'SHIPPING_ADDRESS_FIELD3_CHANGE';
export const ACCEPT_TERMS_CHANGE = 'ACCEPT_TERMS_CHANGE';
